# PlatformIO pre-build hook: read tools/my-buddy/my-buddy.json and emit
# src/my_buddy_defaults.h. The firmware uses these as compile-time
# fallback values for petName / speciesIdx / stateLines, so a fresh
# flash already produces the canonical buddy with no BLE push needed.
# BLE/USB push (cmd: "name" / "species" / "statelines") still works to
# override at runtime — NVS values take priority over compiled defaults.
#
# If my-buddy.json is missing or a field is absent, the corresponding
# default is left empty (firmware then keeps its old generic behavior).
#
# This script is wired up via platformio.ini's `extra_scripts =
# pre:tools/my-buddy/gen_defaults.py`. PlatformIO injects an `Import`
# of `env`, but we don't actually need it — we just write the file.

import json
from pathlib import Path

# When run by PlatformIO via `extra_scripts = pre:...`, this script is
# exec'd by SCons and `__file__` isn't defined. SCons injects the build
# `env`; ask it for the project root. When run standalone (e.g. `python
# tools/my-buddy/gen_defaults.py`), fall back to __file__.
try:
    Import("env")           # noqa: F821 — provided by SCons
    ROOT = Path(env.subst("$PROJECT_DIR"))   # noqa: F821
except Exception:
    ROOT = Path(__file__).resolve().parent.parent.parent

JSON_PATH = ROOT / "tools" / "my-buddy" / "my-buddy.json"
OUT_PATH  = ROOT / "src" / "my_buddy_defaults.h"

# Firmware species table, must match SPECIES_TABLE order in src/buddy.cpp.
FIRMWARE_SPECIES = [
    "capybara", "duck", "goose", "blob", "cat", "dragon", "octopus", "owl",
    "penguin", "turtle", "snail", "ghost", "axolotl", "cactus", "robot",
    "rabbit", "mushroom", "chonk",
]

# Order must match PersonaState enum in src/main.cpp.
STATE_KEYS = ["sleep", "idle", "busy", "attention", "celebrate", "dizzy", "heart"]


def c_escape(s: str) -> str:
    """Make a Python string safe to drop inside a C string literal."""
    return (
        s.replace("\\", "\\\\")
         .replace('"', '\\"')
         .replace("\n", "\\n")
         .replace("\r", "")
    )


def load_buddy():
    if not JSON_PATH.exists():
        return None
    try:
        with open(JSON_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        print(f"[gen_defaults] failed to parse {JSON_PATH}: {e}")
        return None


def render(buddy):
    pet_name = ""
    species_idx = 0xFF   # 0xFF = no compiled default; firmware decides
    lines = ["", "", "", "", "", "", ""]

    if buddy:
        pet_name = (buddy.get("name") or "").strip()
        # Prefer firmwareIdx if present; else look up species name.
        if isinstance(buddy.get("firmwareIdx"), int):
            species_idx = buddy["firmwareIdx"]
        else:
            species = (buddy.get("bones", {}) or {}).get("species")
            if species in FIRMWARE_SPECIES:
                species_idx = FIRMWARE_SPECIES.index(species)
        sl = buddy.get("stateLines", {}) or {}
        for i, k in enumerate(STATE_KEYS):
            v = sl.get(k)
            if isinstance(v, str):
                lines[i] = v.strip()

    out = []
    out.append("// AUTOGENERATED by tools/my-buddy/gen_defaults.py — do not edit.")
    out.append("// Source: tools/my-buddy/my-buddy.json")
    out.append("#pragma once")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f'#define MY_BUDDY_PETNAME      "{c_escape(pet_name)}"')
    out.append(f"#define MY_BUDDY_SPECIES_IDX  {species_idx}")
    out.append("")
    out.append("// Order matches PersonaState: sleep, idle, busy,")
    out.append("// attention, celebrate, dizzy, heart.")
    out.append("static const char* const MY_BUDDY_STATELINES[7] = {")
    for line in lines:
        out.append(f'  "{c_escape(line)}",')
    out.append("};")
    out.append("")
    return "\n".join(out)


def main():
    buddy = load_buddy()
    content = render(buddy)
    # Only rewrite if changed — keeps incremental builds fast.
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    if OUT_PATH.exists() and OUT_PATH.read_text(encoding="utf-8") == content:
        print(f"[gen_defaults] {OUT_PATH.name} unchanged")
        return
    OUT_PATH.write_text(content, encoding="utf-8")
    name = (buddy or {}).get("name") or "(no name)"
    print(f"[gen_defaults] wrote {OUT_PATH.name} for buddy: {name}")


# PlatformIO calls this script with `Import('env')` available; we don't
# need env, just generate the header at import time so it's there before
# compilation starts.
main()
